CREATE DATABASE IF NOT EXISTS bora_pra_obra CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bora_pra_obra;
CREATE TABLE usuarios(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,senha_hash VARCHAR(255) NOT NULL,ativo TINYINT(1) NOT NULL DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE temporadas(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ordem INT NOT NULL,nome VARCHAR(160) NOT NULL,faixa_capitulos VARCHAR(40),objetivo TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE episodios(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,numero INT NOT NULL UNIQUE,titulo VARCHAR(255) NOT NULL,data_gravacao DATE NULL,qtd_arquivos INT NOT NULL DEFAULT 0,temporada_id INT UNSIGNED NULL,etapa VARCHAR(160) NULL,status ENUM('Catalogado','Em edição','Pronto','Agendado','Publicado') NOT NULL DEFAULT 'Catalogado',drive_url VARCHAR(500) NULL,youtube_url VARCHAR(500) NULL,data_publicacao DATETIME NULL,observacoes TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_ep_temp FOREIGN KEY(temporada_id) REFERENCES temporadas(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE ideias(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,titulo VARCHAR(255) NOT NULL,descricao TEXT,status ENUM('Nova','Em análise','Aprovada','Descartada') NOT NULL DEFAULT 'Nova',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
INSERT INTO usuarios(nome,email,senha_hash) VALUES('Administrador','admin@borapraobra.com.br','$2y$12$BKkpzQSDLzjqRh6qYUll8ePFGyXii4kwhvqMqs9.9vydcRMxnqE7m');
INSERT INTO temporadas(ordem,nome,faixa_capitulos,objetivo) VALUES(1,'Preparação do Terreno','001–005','Preparar o terreno para iniciar a construção.');
INSERT INTO temporadas(ordem,nome,faixa_capitulos,objetivo) VALUES(2,'Muro de Arrimo','006–032','Executar toda a contenção do terreno.');
INSERT INTO temporadas(ordem,nome,faixa_capitulos,objetivo) VALUES(3,'Preparação da Casa','033–038','Preparar o terreno para receber a fundação da casa.');
INSERT INTO temporadas(ordem,nome,faixa_capitulos,objetivo) VALUES(4,'Baldrame e Infraestrutura','039–065','Executar fundação, instalações enterradas e contrapiso.');
INSERT INTO temporadas(ordem,nome,faixa_capitulos,objetivo) VALUES(5,'Montagem da Casa em EPS','066–099','Levantar toda a estrutura da residência em painéis EPS.');
INSERT INTO temporadas(ordem,nome,faixa_capitulos,objetivo) VALUES(6,'Laje e Rejuntamento','100–104','Finalizar a estrutura superior e o fechamento das juntas.');
INSERT INTO temporadas(ordem,nome,faixa_capitulos,objetivo) VALUES(7,'Fachada, Impermeabilização e Acabamentos','105–120','Preparar a casa para os acabamentos finais.');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(1,'Poste e Sanepar',5,1,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(2,'Locação Container',4,1,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(3,'Painel Provisório',2,1,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(4,'Poço Artesiano',46,1,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(5,'Visita Inova Blocos Curitiba',2,1,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(6,'Gabarito Muro de Arrimo',1,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(7,'Perfuração Estacas Muro de Arrimo',4,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(8,'Milheiro pros Muros de Arrimo',3,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(9,'Atraso da entrega das colunas de ferro',2,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(10,'Chegada colunas, corte e concretagem',23,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(11,'Criação Caixaria Baldrame',1,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(12,'Concretagem Baldrame do Arrimo',3,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(13,'Levantando Muro de Arrimo',3,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(14,'Levantando Muro de Arrimo pt 2',4,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(15,'Levantando Muro de Arrimo pt 3',10,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(16,'Levantando Muro de Arrimo pt 4',7,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(17,'Levantando Muro de Arrimo pt 5',2,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(18,'Caixaria Viga Cinta Muro Arrimo',2,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(19,'Caixaria Mão Francesa Arrimo',2,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(20,'Aumento Poço + Reforço Caixaria',6,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(21,'Concretagem Viga Cinta + Mão Francesa',6,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(22,'Finalização Viga Cinta + Mão Francesa',1,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(23,'Molhar Mão Francesa + Viga Cinta',4,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(24,'Molhar Francesa + Viga Cinta pt2',2,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(25,'Desenformar caixarias',2,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(26,'Molhar Francesa + Viga Cinta pt3',1,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(27,'Molhar Francesa + Viga Cinta pt4',2,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(28,'Primeiras Cargas de Terra',5,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(29,'Parte 2 Cargas de Terra',3,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(30,'Bobcat nivelamento de terra',2,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(31,'Neutrol no Baldrame',3,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(32,'Finalizando neutrol Mão Francesa',2,2,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(33,'Caminhão compactando terreno',1,3,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(34,'Novas 10 Cargas de Terra',1,3,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(35,'Bobcat espalhando resto da terra',2,3,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(36,'Terraplanagem concluída',1,3,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(37,'Marcação e Gabarito pro Baldrame',2,3,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(38,'Explicações dos Cômodos',2,3,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(39,'Perfuração para Colunas internas',5,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(40,'Corte Colunas Ferro + Buracos',7,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(41,'Concretagem + Buraco Infinito',12,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(42,'Escavação para baldrames casa',5,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(43,'Escavação para baldrames casa pt2',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(44,'Escavação para baldrames casa pt3',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(45,'Caixaria para baldrames casa',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(46,'Caixaria para baldrames casa pt 2',1,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(47,'Caixaria para baldrames casa pt 3',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(48,'Finalização da Caixaria Casa',1,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(49,'Teste funcionamento Rebotermic',3,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(50,'Concretagem Baldrame Casa',13,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(51,'Pós Concretagem Baldrame Casa',1,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(52,'Teste Rebotermic no Concreto',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(53,'Ajustes Terras no Baldrame',1,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(54,'Rebalanceamento da Terra pt 1',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(55,'Rebalanceamento da Terra pt 2',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(56,'Escavação do Encanamento pt 1',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(57,'Escavação do Encanamento pt 2',1,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(58,'Montagem dos Encanamentos pt 1',1,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(59,'Montagem dos Encanamentos pt 2',1,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(60,'Início da Montagem Conduítes',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(61,'Final Aterro + Gabarito Contrapiso',2,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(62,'Correção Encanamento Lavanderia',1,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(63,'Início da Concretagem Contrapiso',26,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(64,'Pós Concretagem e Contrapiso',4,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(65,'Pós Concretagem e Contrapiso pt2',4,4,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(66,'Chegada das Placas e Descarregamento',21,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(67,'Técnico para Ensino da Montagem',34,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(68,'Dia 2 após chegada placas e montagem',22,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(69,'Pós dia 2 revisado no domingo',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(70,'Dia 3 montagem da casa',11,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(71,'Dia 4 montagem da casa',8,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(72,'Dia 5 montagem da casa',10,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(73,'Dia 6 montagem da casa',15,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(74,'Dia 7 montagem da casa',6,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(75,'Dia 8 montagem da casa',2,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(76,'Dia 9 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(77,'Dia 10 montagem da casa',3,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(78,'Dia 11 montagem da casa',7,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(79,'Dia 12 montagem da casa',8,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(80,'Dia 13 montagem da casa',9,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(81,'Dia 14 montagem da casa',2,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(82,'Dia 15 montagem da casa',4,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(83,'Dia 16 montagem da casa',13,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(84,'Dia 17 montagem da casa',5,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(85,'Dia 18 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(86,'Dia 19 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(87,'Dia 20 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(88,'Dia 21 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(89,'Dia 22 montagem da casa',5,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(90,'Dia 23 montagem da casa',5,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(91,'Dia 24 montagem da casa',3,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(92,'Dia 25 montagem da casa',5,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(93,'Dia 26 montagem da casa',9,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(94,'Dia 27 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(95,'Dia 28 montagem da casa',4,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(96,'Dia 29 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(97,'Dia 30 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(98,'Dia 31 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(99,'Dia 32 montagem da casa',1,5,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(100,'9/01 Caixinhas de Luz e Tomada',1,6,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(101,'Concretagem da laje 13/01',12,6,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(102,'Secagem da Laje + Argamassa Rejunte',2,6,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(103,'Continuação Rejunte das Paredes fora',1,6,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(104,'Finalização do Rejunte dentro e fora',1,6,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(105,'Início Montagem das paredes laterais',3,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(106,'Continuação Paredes + Início Fachada',1,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(107,'Montagem Caixaria baldrame fachada',2,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(108,'Início montagem parede fachada',2,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(109,'Carregando terra + Nivelamento quintal',3,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(110,'Várias atualizações em um único vídeo',5,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(111,'Tentativa de compactar terra',1,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(112,'VBrasil + Tinta + Massa Corrida',4,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(113,'Impermeabilizante 4 em 1 Viapol + VBrasil paredes de fora',4,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(114,'Laje: argamassa para lugares empossados',1,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(115,'Viapol nas paredes externas dentro da casa',1,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(116,'Mudança do Cavalete de Água fora da casa',1,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(117,'Neutrol baldrame exterior + problemas Viapol + nova camada na laje',1,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(118,'Limpeza Interna + Lavagem das Paredes',13,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(119,'Tratamento das Juntas: Fita + Massa + Fundo preparador',2,7,'Catalogado');
INSERT INTO episodios(numero,titulo,qtd_arquivos,temporada_id,status) VALUES(120,'Tratamento Juntas Fita + Massa Pt 2',1,7,'Catalogado');